// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1CmJPuUB1OGPk4JBdvulYLXGQjIKQOV4',
    appId: '1:120331822819:web:061fd48f5315952ce4c7d6',
    messagingSenderId: '120331822819',
    projectId: 'real-estate-project-5a668',
    authDomain: 'real-estate-project-5a668.firebaseapp.com',
    storageBucket: 'real-estate-project-5a668.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0LMzj6YxO6hIUDfmvUZWJTVWIdcpBPCU',
    appId: '1:120331822819:android:93a9801309c50611e4c7d6',
    messagingSenderId: '120331822819',
    projectId: 'real-estate-project-5a668',
    storageBucket: 'real-estate-project-5a668.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSjasEHcjLz8l9pXbgsDS6KWuHctyTrwI',
    appId: '1:120331822819:web:f0a1047aad05e2e2e4c7d6',
    messagingSenderId: '120331822819',
    projectId: 'real-estate-project-5a668',
    authDomain: 'real-estate-project-5a668.firebaseapp.com',
    storageBucket: 'real-estate-project-5a668.appspot.com',
  );

}